/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fees_management_system;
import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author Divya
 */
public class PrintReciept extends javax.swing.JFrame {

    /**
     * Creates new form PrintReciept
     */
    public PrintReciept() {
        initComponents();
        getRecords();
        Container c=getContentPane();
        c.setBackground(new Color(204,204,255));
    }
    
    public void getRecords(){
            try{
          Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
          Connection con= DriverManager.getConnection("jdbc:derby://localhost:1527/signupdata","divya","divya");
        PreparedStatement pst=con.prepareStatement("select * from fees_details order by reciept_no desc fetch first 1 row only");
        ResultSet rs=pst.executeQuery();
        rs.next();
        txt_Reciept.setText(rs.getString("reciept_no"));
        //setting data for payment mode
          txt_Payment.setText(rs.getString("payment_mode"));
          
          String paymentMode=rs.getString("payment_mode");
          if(paymentMode.equalsIgnoreCase("cash")){
             
               lbl_DD.setText("");
               
              txt_DDcheque.setText(" ");
              txt_Bank.setText(" "); 
          }
          if(paymentMode.equalsIgnoreCase("cheque")){
             lbl_DD.setText("");
              txt_DDcheque.setText(rs.getString("cheque_no"));
              txt_Bank.setText(rs.getString("bank_name")); 
          }
           if(paymentMode.equalsIgnoreCase("dd")){
              
              txt_DDcheque.setText(rs.getString("dd_no"));
              txt_Bank.setText(rs.getString("bank_name")); 
          }
           if(paymentMode.equalsIgnoreCase("card")){
              lbl_DD.setText("");

              txt_Bank.setText(rs.getString("bank_name")); 
          } 
         //setting data for username
         txt_Recieved.setText(rs.getString("student_name"));
          txt_year1.setText(rs.getString("year1"));
           txt_year2.setText(rs.getString("year2"));
            txt_Course.setText(rs.getString("course_name"));
             txt_Amount.setText(rs.getString("amount"));
              txt_Total.setText(rs.getString("total_amount"));
               txt_Words.setText(rs.getString("total_in_words"));
                txt_Remark.setText(rs.getString("remark"));
       } 
       catch(Exception e){
           e.printStackTrace();
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelsideBar = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        btnHome = new javax.swing.JLabel();
        panelSearch = new javax.swing.JPanel();
        btnSearch = new javax.swing.JLabel();
        panelEditCourse = new javax.swing.JPanel();
        btnEditCourse = new javax.swing.JLabel();
        panelRecord = new javax.swing.JPanel();
        btnRecord = new javax.swing.JLabel();
        panelBack = new javax.swing.JPanel();
        btnBack = new javax.swing.JLabel();
        panelLogout = new javax.swing.JPanel();
        btnLogout = new javax.swing.JLabel();
        panelPrint = new javax.swing.JPanel();
        btnPrint = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panel_Print = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txt_DDcheque = new javax.swing.JLabel();
        txt_Payment = new javax.swing.JLabel();
        lbl_Cheque = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_Bank = new javax.swing.JLabel();
        txt_Words = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txt_year1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_Sgst = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txt_Remark = new javax.swing.JLabel();
        txt_Cgst = new javax.swing.JLabel();
        txt_year2 = new javax.swing.JLabel();
        txt_Recieved = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_Reciept = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lbl_DD = new javax.swing.JLabel();
        lbl_Bank = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_Course = new javax.swing.JLabel();
        txt_Amount = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_Total = new javax.swing.JLabel();
        txt_Amount3 = new javax.swing.JLabel();
        txt_Amount4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsideBar.setBackground(new java.awt.Color(51, 51, 51));
        panelsideBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHome.setBackground(new java.awt.Color(153, 204, 255));
        panelHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btnHome.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/home.png"))); // NOI18N
        btnHome.setText("            HOME");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addComponent(btnHome)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelsideBar.add(panelHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 280, 70));

        panelSearch.setBackground(new java.awt.Color(74, 124, 174));
        panelSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btnSearch.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/search2.png"))); // NOI18N
        btnSearch.setText("   SEARCH RECORD");
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSearch))
        );

        panelsideBar.add(panelSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 280, 70));

        panelEditCourse.setBackground(new java.awt.Color(246, 167, 114));
        panelEditCourse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btnEditCourse.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnEditCourse.setForeground(new java.awt.Color(255, 255, 255));
        btnEditCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/edit2.png"))); // NOI18N
        btnEditCourse.setText("     EDIT COURSES");
        btnEditCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditCourseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditCourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditCourseMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEditCourseLayout = new javax.swing.GroupLayout(panelEditCourse);
        panelEditCourse.setLayout(panelEditCourseLayout);
        panelEditCourseLayout.setHorizontalGroup(
            panelEditCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditCourseLayout.createSequentialGroup()
                .addComponent(btnEditCourse)
                .addGap(0, 41, Short.MAX_VALUE))
        );
        panelEditCourseLayout.setVerticalGroup(
            panelEditCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEditCourseLayout.createSequentialGroup()
                .addComponent(btnEditCourse)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelsideBar.add(panelEditCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 280, 70));

        panelRecord.setBackground(new java.awt.Color(238, 73, 114));
        panelRecord.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btnRecord.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnRecord.setForeground(new java.awt.Color(255, 255, 255));
        btnRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/view all record.png"))); // NOI18N
        btnRecord.setText(" VIEW ALL RECORD");
        btnRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRecordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelRecordLayout = new javax.swing.GroupLayout(panelRecord);
        panelRecord.setLayout(panelRecordLayout);
        panelRecordLayout.setHorizontalGroup(
            panelRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecordLayout.createSequentialGroup()
                .addComponent(btnRecord)
                .addGap(0, 29, Short.MAX_VALUE))
        );
        panelRecordLayout.setVerticalGroup(
            panelRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecordLayout.createSequentialGroup()
                .addComponent(btnRecord)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelsideBar.add(panelRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, 70));

        panelBack.setBackground(new java.awt.Color(153, 204, 0));
        panelBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btnBack.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/left-arrow.png"))); // NOI18N
        btnBack.setText("       BACK");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBackLayout = new javax.swing.GroupLayout(panelBack);
        panelBack.setLayout(panelBackLayout);
        panelBackLayout.setHorizontalGroup(
            panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackLayout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        panelBackLayout.setVerticalGroup(
            panelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackLayout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelsideBar.add(panelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, 70));

        panelLogout.setBackground(new java.awt.Color(153, 67, 153));
        panelLogout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btnLogout.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/logout.png"))); // NOI18N
        btnLogout.setText("       LOGOUT");
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelLogoutLayout = new javax.swing.GroupLayout(panelLogout);
        panelLogout.setLayout(panelLogoutLayout);
        panelLogoutLayout.setHorizontalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoutLayout.createSequentialGroup()
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        panelLogoutLayout.setVerticalGroup(
            panelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogoutLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogout))
        );

        panelsideBar.add(panelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 280, 70));

        panelPrint.setBackground(new java.awt.Color(255, 255, 51));
        panelPrint.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));

        btnPrint.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fees_management_system/images/printer-.png"))); // NOI18N
        btnPrint.setText("     PRINT");
        btnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrintMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrintMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrintMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelPrintLayout = new javax.swing.GroupLayout(panelPrint);
        panelPrint.setLayout(panelPrintLayout);
        panelPrintLayout.setHorizontalGroup(
            panelPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrintLayout.createSequentialGroup()
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE))
        );
        panelPrintLayout.setVerticalGroup(
            panelPrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelsideBar.add(panelPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 280, 70));

        getContentPane().add(panelsideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 650));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 6, -1, -1));

        panel_Print.setBackground(new java.awt.Color(255, 255, 255));
        panel_Print.setForeground(new java.awt.Color(0, 51, 102));
        panel_Print.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("KIT INSTITUTE");
        panel_Print.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        panel_Print.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 700, -1));

        txt_DDcheque.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_DDcheque.setText("DD  :");
        panel_Print.add(txt_DDcheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 100, 20));

        txt_Payment.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_Payment.setText("Payment Mode  :");
        panel_Print.add(txt_Payment, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        lbl_Cheque.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_Cheque.setText("Cheque no  :");
        panel_Print.add(lbl_Cheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel6.setText("Amount  ");
        panel_Print.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, -1, 30));

        txt_Bank.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_Bank.setText("Bank Name  :");
        panel_Print.add(txt_Bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        txt_Words.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_Words.setText("Total in words  :");
        panel_Print.add(txt_Words, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 51, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 102));
        panel_Print.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 230, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 51, 102));
        jSeparator2.setForeground(new java.awt.Color(0, 51, 102));
        panel_Print.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 630, 10));

        txt_year1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_year1.setText("2021");
        panel_Print.add(txt_year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel10.setText("Sr no.  ");
        panel_Print.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 261, -1, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel11.setText("1.");
        panel_Print.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 30));

        txt_Sgst.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_Sgst.setText("SGST 9%");
        panel_Print.add(txt_Sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 51, 102));
        jSeparator3.setForeground(new java.awt.Color(0, 51, 102));
        panel_Print.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 630, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 51, 102));
        jSeparator4.setForeground(new java.awt.Color(0, 51, 102));
        panel_Print.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 230, 10));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel13.setText("Payment for the year  :");
        panel_Print.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        txt_Remark.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_Remark.setText("Remark :");
        panel_Print.add(txt_Remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, -1, 30));

        txt_Cgst.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_Cgst.setText("CGST 9%");
        panel_Print.add(txt_Cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, -1, 30));

        txt_year2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_year2.setText("2022");
        panel_Print.add(txt_year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        txt_Recieved.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_Recieved.setText("recieved from");
        panel_Print.add(txt_Recieved, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel18.setText("  -");
        panel_Print.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 30, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel19.setText("Reciept no.  :");
        panel_Print.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        txt_Reciept.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_Reciept.setText("Reciept no.  :");
        panel_Print.add(txt_Reciept, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel21.setText("Payment Mode  :");
        panel_Print.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        lbl_DD.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_DD.setText("DD  :");
        panel_Print.add(lbl_DD, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 100, 20));

        lbl_Bank.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lbl_Bank.setText("Bank Name  :");
        panel_Print.add(lbl_Bank, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel24.setText("22HVSJH55");
        panel_Print.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel25.setText("Recieved From  :");
        panel_Print.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel26.setText("GSTIN :");
        panel_Print.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel17.setText("Head");
        panel_Print.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel20.setText("CGST 9%");
        panel_Print.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel14.setText("SGST 9%");
        panel_Print.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, 30));

        txt_Course.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_Course.setText("Head");
        panel_Print.add(txt_Course, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, 30));

        txt_Amount.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_Amount.setText("Initial Amount");
        panel_Print.add(txt_Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, -1, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel12.setText("Total in words  :");
        panel_Print.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, -1, -1));

        txt_Total.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_Total.setText("Total Amount");
        panel_Print.add(txt_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, -1, 30));

        txt_Amount3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_Amount3.setText("Reciever's Signature");
        panel_Print.add(txt_Amount3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, -1, 30));

        txt_Amount4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txt_Amount4.setText("Remark :");
        panel_Print.add(txt_Amount4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, 30));

        getContentPane().add(panel_Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 700, 580));

        jLabel2.setFont(new java.awt.Font("Broadway", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRINT RECIEPT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 230, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(51,153,255);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
        Color clr=new Color(153,204,255);
        panelHome.setBackground(clr);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(8,82,119);
        panelSearch.setBackground(clr);

    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        // TODO add your handling code here:
        Color clr=new Color(74,124,174);
        panelSearch.setBackground(clr);
    }//GEN-LAST:event_btnSearchMouseExited

    private void btnEditCourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCourseMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(255,102,51);
        panelEditCourse.setBackground(clr);
    }//GEN-LAST:event_btnEditCourseMouseEntered

    private void btnEditCourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCourseMouseExited
        // TODO add your handling code here:
        Color clr=new Color(246,167,114);
        panelEditCourse.setBackground(clr);
    }//GEN-LAST:event_btnEditCourseMouseExited

    private void btnRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecordMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(204,0,102);
        panelRecord.setBackground(clr);
    }//GEN-LAST:event_btnRecordMouseEntered

    private void btnRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecordMouseExited
        // TODO add your handling code here:
        Color clr=new Color(238,73,114);
        panelRecord.setBackground(clr);
    }//GEN-LAST:event_btnRecordMouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(120,159,5);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        // TODO add your handling code here:
        Color clr=new Color(153,204,0);
        panelBack.setBackground(clr);
    }//GEN-LAST:event_btnBackMouseExited

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        Color clr=new Color(102,0,102);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        Color clr=new Color(153,67,153);
        panelLogout.setBackground(clr);
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnPrintMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseEntered
        // TODO add your handling code here:
         Color clr=new Color(255,204,0);
        panelPrint.setBackground(clr);
    }//GEN-LAST:event_btnPrintMouseEntered

    private void btnPrintMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseExited
        // TODO add your handling code here:
         Color clr=new Color(255,255,51);
        panelPrint.setBackground(clr);
    }//GEN-LAST:event_btnPrintMouseExited

    private void btnPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrintMouseClicked
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.70,0.70);
                
                panel_Print.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
     
    }//GEN-LAST:event_btnPrintMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        Signup_Page sign=new Signup_Page();
        sign.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
         AddFees add=new AddFees();
         add.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
           home h=new home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        SearchRecord search=new SearchRecord();
        search.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnEditCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditCourseMouseClicked
        // TODO add your handling code here:
         EditCourse edit=new EditCourse();
        edit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEditCourseMouseClicked

    private void btnRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRecordMouseClicked
        // TODO add your handling code here:
         ViewAllRecord view=new ViewAllRecord();
        view.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRecordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReciept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReciept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnEditCourse;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnLogout;
    private javax.swing.JLabel btnPrint;
    private javax.swing.JLabel btnRecord;
    private javax.swing.JLabel btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_Bank;
    private javax.swing.JLabel lbl_Cheque;
    private javax.swing.JLabel lbl_DD;
    private javax.swing.JPanel panelBack;
    private javax.swing.JPanel panelEditCourse;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelPrint;
    private javax.swing.JPanel panelRecord;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JPanel panel_Print;
    private javax.swing.JPanel panelsideBar;
    private javax.swing.JLabel txt_Amount;
    private javax.swing.JLabel txt_Amount3;
    private javax.swing.JLabel txt_Amount4;
    private javax.swing.JLabel txt_Bank;
    private javax.swing.JLabel txt_Cgst;
    private javax.swing.JLabel txt_Course;
    private javax.swing.JLabel txt_DDcheque;
    private javax.swing.JLabel txt_Payment;
    private javax.swing.JLabel txt_Reciept;
    private javax.swing.JLabel txt_Recieved;
    private javax.swing.JLabel txt_Remark;
    private javax.swing.JLabel txt_Sgst;
    private javax.swing.JLabel txt_Total;
    private javax.swing.JLabel txt_Words;
    private javax.swing.JLabel txt_year1;
    private javax.swing.JLabel txt_year2;
    // End of variables declaration//GEN-END:variables
}
